Debugging failing CI workflow
I'm seeing:

Run pnpm/action-setup@v2.2.4
  with:
    version: 8.15.9
    dest: ~/setup-pnpm
    run_install: null
  env:
    TURBO_TOKEN:
    TURBO_TEAM:
    DATABASE_URL: file:./db.sqlite
Running self-installer...
   WARN  GET https://registry.npmjs.org/pnpm error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
   WARN  GET https://registry.npmjs.org/pnpm error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
   ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/pnpm: Value of "this" must be of type URLSearchParams
Error: Something went wrong, self-installer exits with code 1
Installation Completed!

I'm going to try installing node first because of a snippet I found on the internet.